WillsPlatform/WillsPlatform/Models/Forms/CreateFormViewModel.cs
using WillsPlatform.Application.DTOs;

namespace WillsPlatform.Web.Models.Forms
{
    public class FormViewModel
    {
       public int FormId { get; set; }
       public IEnumerable<QuestionDTO> Questions { get; set; } = new List<QuestionDTO>();
    }
}

WillsPlatform/WillsPlatform/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;
using WillsPlatform.Application.DTOs;
using WillsPlatform.Application.Services;
using WillsPlatform.Web.Models.Forms;

namespace WillsPlatform.Web.Controllers
{
    public class FormController : Controller
    {
        private readonly IFormService _formService;

        public FormController(IFormService formService)
        {
            _formService = formService;
        }

        public async Task<IActionResult> Create(int id)
        {
            var questions = await  _formService.GetFormQuestionsAsync(id); 
            
            return View( new FormViewModel () {
                FormId = id, Questions = questions 
            });
        }      

        [HttpPost]
        public async Task<IActionResult> Generate(FormViewModel model, IFormCollection collection)
        {
            try
            {
                //Fetch Template based on form.
                var template = await _formService.GetFormTemplateAsync(model.FormId);

                //Parse template tockens by user inputs.
                var templatecontent = ParseTemplate(template, collection);
                var parsedContent = BuildFormContent(templatecontent);
                return File(Encoding.UTF8.GetBytes(parsedContent), "application/vnd.ms-word", "Will.doc");
            }
            catch(Exception ex)
            {
                string exceptionMessage = ex.Message;
                return RedirectToAction(nameof(Create),model.FormId);
            }
        }

        #region Helper Methods --
        private string ParseTemplate(TemplateDTO template, IFormCollection userInputs)
        {
            var content = template.Text ?? string.Empty;
            var tokens = template.Tokens ?? new List<TokenDTO>();

            foreach (var tok in tokens)
            {
                if (userInputs.ContainsKey(tok.Name))
                    content = content?.Replace(tok.Text, userInputs[tok.Name]);
            }
            
            return BuildFormContent(content);
        }

        private string BuildFormContent(string htmlTemplateContent)
        {
            //build the content for the dynamic Word document
            //in HTML alongwith some Office specific style properties. 
            var strBody = new StringBuilder();

            strBody.Append("<html " +
             "xmlns:o='urn:schemas-microsoft-com:office:office' " +
             "xmlns:w='urn:schemas-microsoft-com:office:word'" +
              "xmlns='http://www.w3.org/TR/REC-html40'>" +
              "<head><title>Time</title>");

            //The setting specifies document's view after it is downloaded as Print
            //instead of the default Web Layout
            strBody.Append("<!--[if gte mso 9]>" +
             "<xml>" +
             "<w:WordDocument>" +
             "<w:View>Print</w:View>" +
             "<w:Zoom>90</w:Zoom>" +
             "<w:DoNotOptimizeForBrowser/>" +
             "</w:WordDocument>" +
             "</xml>" +
             "<![endif]-->");

            strBody.Append("<style>" +
             "<!-- /* Style Definitions */" +
             "@page Section1" +
             "   {size:8.5in 11.0in; " +
             "   margin:1.0in 1.25in 1.0in 1.25in ; " +
             "   mso-header-margin:.5in; " +
             "   mso-footer-margin:.5in; mso-paper-source:0;}" +
             " div.Section1" +
             "   {page:Section1;}" +
             "-->" +
             "</style></head>");

            strBody.Append("<body lang=EN-US style='tab-interval:.5in'>" +
             "<div class=Section1>");
            strBody.Append(htmlTemplateContent ?? string.Empty);
            strBody.Append("</div></body></html>");

            return strBody.ToString();
        }

        #endregion
    }
}

WillsPlatform/WillsPlatform/Views/Form/Create.cshtml
@using WillsPlatform.Application.Enumerations
@using WillsPlatform.Web.Models.Forms;
@{
    ViewData["Title"] = "Create";
    @model FormViewModel

}

<div class="pagetitle">
    <h1>Create</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/">Forms</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Form Information</h5>
                    <form asp-action="Generate" asp-controller="Form" method="post" class="row g-3">
                        <input type="hidden" asp-for="@Model.FormId" />
                        @foreach (var objQ in Model.Questions)
                        {
                            @if (objQ.Field.Id != FieldTypes.RadioButton.Value)
                            {
                                <div class="col-md-12">
                                    @if (objQ.Field.Id != FieldTypes.Checkbox.Value)
                                    {
                                        <div class="form-floating mb-3">
                                            <question field-name="@objQ.Name" class="form-control" id="floatingName" placeholder="Your Name" field-type="@objQ.Field.Id"></question>
                                            <label for="floatingName">@objQ.Text</label>
                                        </div>
                                    }
                                    @if (objQ.Field.Id == FieldTypes.Checkbox.Value)
                                    {
                                        <legend class="col-form-label col-sm-2 pt-0">@objQ.Text</legend>
                                        <question field-name="@objQ.Name" class="col-sm-10" field-type="@objQ.Field.Id"></question>
                                    }
                                </div>
                            }
                            @if (objQ.Field.Id == FieldTypes.RadioButton.Value)
                            {
                                <fieldset>
                                    <legend class="col-form-label col-sm-2 pt-0">@objQ.Text</legend>
                                    <question field-name="@objQ.Name" class="col-sm-10" field-type="@objQ.Field.Id"></question>
                                </fieldset>
                            }
                            
                        }
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Generate</button>
                            <button type="reset" class="btn btn-secondary">Reset</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

WillsPlatform/WillsPlatform/Views/Form/FormsList.cshtml
@using WillsPlatform.Web.Models.Forms
@model FormListVM

@{
    ViewData["Title"] = "Questionnaires";
}

<div class="pagetitle">
    <h1>Forms</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Form</li>
        </ol>
    </nav>
</div>
<section class="section">  
    <div class="row">
        <div class="col-12">
            <div class="card recent-sales overflow-auto">

                <div class="card-body">
                    <h5 class="card-title">Questionnaires<span>| Management</span> <button class="btn btn-primary float-end">Add New</button></h5>
                    <table class="table table-borderless datatable">
                        <thead>
                            <tr>
                                <th scope="col">S.No</th>
                                <th scope="col">Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                foreach (var form in Model.Forms)
                                {

                                    <tr>
                                        <th scope="row"><a href="#">#@i</a></th>
                                        <td>@form.Name</td>
                                    </tr>
                                    {
                                        i++;
                                    }
                                }
                            }
                        </tbody>
                    </table>

                </div>

            </div>
        </div><!-- End Recent Sales -->
    </div>
</section>